[versions]

kotlin = "1.9.10"
detekt = "1.23.1"

[libraries]

detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0"

[plugins]
